version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
     - postgres:/data/postgres

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379

volumes:
    postgres: